apiVersion: 1.0
image:
  imageType: iso
  arch: x86_64
  baseImage: SLE-Micro.iso
  outputImageName: eib-image.iso
operatingSystem:
  isoConfiguration:
    installDevice: /dev/sda
  time:
    timezone: America/Chicago
    ntp:
      forceWait: true
      pools:
        - time.google.com
  users:
  - username: root
    encryptedPassword: 
  keymap: us
  systemd:
    enable:
      - open-vm-tools
  packages:
    noGPGCheck: false
    packageList:
      - nfs-client
      - nfs-kernel-server
      - rpcbind
      - mdadm
      - multipath-tools
      - gptfdisk
      - device-mapper
      - iperf
      - open-vm-tools
      - url:
        unsigned: true
    sccRegistrationCode: 